apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: clusterroles-spawner-rules
parameters:
- name: NAME_PREFIX
  value: ""
  required: false
- name: WORKSHOP_NAME
  value: ""
  required: true
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_MODE
  value: "learning-portal"
  required: true
objects:
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    name: ${NAME_PREFIX}${WORKSHOP_NAME}-spawner-rules
    labels:
      app: ${NAME_PREFIX}${WORKSHOP_NAME}
      spawner: ${SPAWNER_MODE}
      class: spawner
  rules:
  - apiGroups:
    - ""
    - authorization.openshift.io
    - rbac.authorization.k8s.io
    resourceNames:
    - strimzi-cluster-operator-namespaced
    - strimzi-cluster-operator-global
    - strimzi-kafka-broker
    - strimzi-entity-operator
    - strimzi-topic-operator
    resources:
    - clusterroles
    verbs:
    - bind
