---
# tasks file for lab-developing-with-odo
- debug:
    msg: "BEGIN - COMMON DEFINITIONS"

- name: login as super user with pwd
  command: "oc login {{ master_url }} -u {{ admin_user }} -p {{ admin_password }} --insecure-skip-tls-verify=true"

- debug:
    msg: "END - COMMON DEFINITIONS"