---
# tasks file for lab
- debug:
    msg: "Installing {{ __lab_name }} homeroom lab in {{ namespace }}"

- debug:
    var: images_to_prepull

- name: Process prepull template
  template:
    src: ./templates/prepull.yaml.j2
    dest: /tmp/prepull.yaml

- name: Check for nodeselector compute
  command: oc get nodes -l node-role.kubernetes.io/compute -o jsonpath='{ .items[*].metadata.name }'
  register: compute_nodes

- name: Check for nodeselector worker
  command: oc get nodes -l node-role.kubernetes.io/worker -o jsonpath='{ .items[*].metadata.name }'
  register: worker_nodes

- set_fact:
    nodeselector: "node-role.kubernetes.io/compute: 'true'"
  when: compute_nodes.stdout != ''

- set_fact:
    nodeselector: "node-role.kubernetes.io/worker:"
  when: worker_nodes.stdout != ''

- name: Create DaemonSet to Prepull images (targeting worker/compute nodes if defined, else all)
  k8s:
    state: present
    src: /tmp/prepull.yaml
    namespace: "{{ namespace }}"

- name: Wait for images to be prepulled
  command: oc rollout status daemonset/prepull-{{ __lab_name }} -n {{ namespace }}

- name: Create homeroom resources
  shell: >
    oc process -f {{ homeroom_template_path }} \
    --param APPLICATION_NAME="{{ homeroom_app_name }}" | oc apply -n {{ namespace }} -f -

- name: Wait for the homeroom to deploy
  command: oc rollout status dc/{{ homeroom_app_name }} -n {{ namespace }}

- name: Get homeroom Route
  k8s_facts:
    api_version: "route.openshift.io/v1"
    kind: Route
    name: "{{ homeroom_app_name }}"
    namespace: "{{ namespace }}"
  register: homeroom_route

- set_fact:
    homeroom_route_url: "https://{{ homeroom_route.resources[0].spec.host }}"

- name: Create workshop resources
  shell: >
    oc process -f {{ spawner_template_path }} \
    --param APPLICATION_NAME="{{ __lab_name }}" \
    --param PROJECT_NAME="{{ namespace }}" \
    --param HOMEROOM_LINK="{{ homeroom_route_url }}" \
    --param RESOURCE_BUDGET="{{ resource_budget }}" \
    --param GATEWAY_ENVVARS="{{ gateway_envvars }}" \
    --param TERMINAL_ENVVARS="{{ terminal_envvars }}" \
    --param WORKSHOP_ENVVARS="{{ workshop_envvars }}" \
    --param LETS_ENCRYPT="{{ lets_encrypt }}" | oc apply -n {{ namespace }} -f -

- name: Wait for the spawner to deploy
  command: oc rollout status dc/{{ __lab_name }} -n {{ namespace }}

# oc apply -f .workshop/resources/ --recursive
- name: Apply global definitions
  command: oc apply -f {{ role_path }}/files/resources/ --recursive

- name: Update spawner configuration for workshop
  shell: >
     oc process -f {{ item }} \
     --param JUPYTERHUB_APPLICATION="{{ __lab_name }}" \
     --param JUPYTERHUB_NAMESPACE="{{ namespace }}" | oc apply -n {{ namespace }} -f -
  loop:
  - "{{ role_path }}/files/templates/clusterroles-session-rules.yaml"
  - "{{ role_path }}/files/templates/clusterroles-spawner-rules.yaml"
  - "{{ role_path }}/files/templates/configmap-extra-resources.yaml"

- name: Restart the spawner with new configuration
  command: oc rollout latest dc/{{ __lab_name }} -n {{ namespace }}

- name: Wait for spawner to be restarted
  command: oc rollout status dc/{{ __lab_name }} -n {{ namespace }}

- name: Updating spawner to use image for workshop
  command: oc tag "{{ __workshop_image }}" "{{ __lab_name }}-app:latest" -n {{ namespace }}

- name: Get homeroom Route
  k8s_facts:
    api_version: "route.openshift.io/v1"
    kind: Route
    name: "{{ __lab_name }}"
    namespace: "{{ namespace }}"
  register: lab_route

- set_fact:
    lab_url: "https://{{ lab_route.resources[0].spec.host }}"

- name: Get homeroom configmap content
  shell: oc get cm/{{ homeroom_app_name }}-cfg -o jsonpath='{ .data.workshops\.json }' -n {{ namespace }}
  register: homeroom_cm_data

- set_fact:
    homeroom_cm_json: "{{ homeroom_cm_data.stdout | from_json }}"

- set_fact:
    workshop_present: "{{ homeroom_cm_json | json_query(my_query) }}"
  vars:
    my_query: "[?title=='{{ __lab_name }}']"

# If it's there do nothing, else, add it

- set_fact:
    workshop_list: "{{ ( homeroom_cm_json | union(this_workshop_json)) | default(homeroom_cm_json) }}"
  when: not workshop_present

- name: Write homeroom configuration to a file
  copy:
    dest: /tmp/configmap.json
    content: "{{ workshop_list | to_nice_json }}"
  when: workshop_list is defined

- name: Update CM
  shell: oc create configmap {{ homeroom_app_name }}-cfg --from-file=workshops.json=/tmp/configmap.json --dry-run -o yaml | oc replace -n {{ namespace }} -f -
  when: workshop_list is defined

- name: Rollout homeroom to pickup config changes
  command: oc rollout latest dc/{{ homeroom_app_name }} -n {{ namespace }}

- name: Wait for homeroom to be ready again
  command: oc rollout status dc/{{ homeroom_app_name }} -n {{ namespace }}
